services:
  app:
    build:
      args:
        user: crud
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crud/laravel-api
    container_name: crud-api
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./storage:/var/www/storage
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  pgsql:
    image: postgres:12.17
    container_name: pgsql
    restart: always
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

  minio:
    image: minio/minio
    container_name: minio_rcp
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    ports:
      - "${PORT:-9000}:9000" # Alterei as portas para evitar conflitos
      - "${PORT_ADMIN:-9001}:9001"
    networks:
      - docker-laravel

networks:
  docker-laravel:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
